import axios from "axios";
import { prisma } from "../lib/prisma.js";
import { env } from "../config/env.js";
import { getAccessToken } from "./spotifyAuth.service.js";
import { getGroqText } from "./groq.service.js";
import type {
  Track,
  ResolvedTrack,
  SpotifySearchResponse,
  SpotifyPlaylistResponse,
  GeneratePlaylistResponse,
} from "../types/index.js";

const SPOTIFY_API_URL = "https://api.spotify.com/v1";

// ─── Utility ──────────────────────────────────────────────────────────────────

function sanitizeText(text: string): string {
  if (!text) return "";
  return text
    .replace(/\(.*?\)/g, "")
    .replace(/\[.*?\]/g, "")
    .split(/feat\.?|ft\.?|featuring/i)[0]!
    .trim();
}

// ─── Step 1: Search ───────────────────────────────────────────────────────────

async function searchTrack(
  track: Track,
  accessToken: string
): Promise<ResolvedTrack | null> {
  const cleanTitle = sanitizeText(track.title);
  const firstArtist = track.artist.split(",")[0] || track.artist;
  const primaryArtist = sanitizeText(firstArtist);

  const executeSearch = async (query: string, limit: number = 5) => {
    const { data } = await axios.get<SpotifySearchResponse>(
      `${SPOTIFY_API_URL}/search`,
      {
        headers: { Authorization: `Bearer ${accessToken}` },
        params: { q: query, type: "track", limit },
      }
    );
    return data.tracks?.items || [];
  };

  try {
    // Pass 1: Strict quoted fields with clean title/artist
    let items = await executeSearch(
      `track:"${cleanTitle}" artist:"${primaryArtist}"`
    );

    // Pass 2: Clean title + artist unquoted
    if (items.length === 0) {
      console.log(`[Waterfall] Pass 1 failed for "${track.title}". Trying Pass 2...`);
      items = await executeSearch(`${cleanTitle} ${primaryArtist}`);
    }

    // Pass 3: Original unsanitized title + original artist
    if (items.length === 0) {
      console.log(`[Waterfall] Pass 2 failed for "${track.title}". Trying Pass 3...`);
      items = await executeSearch(`${track.title} ${track.artist}`);
    }

    // Pass 4: Original title + first artist only
    if (items.length === 0) {
      console.log(`[Waterfall] Pass 3 failed for "${track.title}". Trying Pass 4...`);
      const firstOriginalArtist = track.artist.split(",")[0]!.trim();
      items = await executeSearch(`${track.title} ${firstOriginalArtist}`);
    }

    // Pass 5: Clean title only
    if (items.length === 0) {
      console.log(`[Waterfall] Pass 4 failed for "${track.title}". Trying Pass 5...`);
      items = await executeSearch(`${cleanTitle}`, 10);
    }

    // Pass 6: Original title only — catches "Happy - From Despicable Me 2" etc
    if (items.length === 0) {
      console.log(`[Waterfall] Pass 5 failed for "${track.title}". Trying Pass 6...`);
      // Strip everything after " - " or " — " which are usually subtitle/movie info
      const baseTitle = track.title.split(/ [-—] /)[0]!.trim();
      items = await executeSearch(`${baseTitle} ${primaryArtist}`, 10);
    }

    // Pass 7: Base title only
    if (items.length === 0) {
      console.log(`[Waterfall] Pass 6 failed for "${track.title}". Trying Pass 7...`);
      const baseTitle = track.title.split(/ [-—] /)[0]!.trim();
      items = await executeSearch(`${baseTitle}`, 15);
    }

    if (items.length === 0) {
      console.warn(`[Spotify] Exhausted all passes. Not found: "${track.title}"`);
      return null;
    }

    const bestMatch =
      items.find((item) =>
        item.artists.some(
          (a) =>
            a.name.toLowerCase().includes(primaryArtist.toLowerCase()) ||
            primaryArtist.toLowerCase().includes(a.name.toLowerCase())
        )
      ) ?? items[0];

    if (!bestMatch) return null;

    return {
      title: bestMatch.name,
      artist: bestMatch.artists.map((a) => a.name).join(", "),
      spotifyUri: bestMatch.uri,
      spotifyUrl: bestMatch.external_urls.spotify,
      albumArt: bestMatch.album?.images?.[0]?.url,
    };
  } catch (err) {
    console.error(`[Spotify] Search error for "${track.title}":`, err);
    return null;
  }
}

// ─── Step 2: Create playlist ──────────────────────────────────────────────────

async function createPlaylist(
  accessToken: string,
  name: string
): Promise<string> {
  try {
    const { data } = await axios.post<SpotifyPlaylistResponse>(
      `${SPOTIFY_API_URL}/me/playlists`,
      {
        name,
        description: "Generated by Symphony 🎵 — AI-powered playlist creator",
        public: true,
      },
      {
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
      }
    );
    console.log(`[Spotify] Playlist created with ID: ${data.id}`);
    return data.id;
  } catch (err: any) {
    console.error(
      "[Spotify Error] createPlaylist failed:",
      err.response?.data || err.message
    );
    throw new Error("Failed to create Spotify playlist.");
  }
}

// ─── Step 3: Add tracks ───────────────────────────────────────────────────────

async function addTracksToPlaylist(
  playlistId: string,
  uris: string[],
  accessToken: string
): Promise<void> {
  const chunks: string[][] = [];
  for (let i = 0; i < uris.length; i += 100) {
    chunks.push(uris.slice(i, i + 100));
  }

  try {
    for (const chunk of chunks) {
      await axios.post(
        `${SPOTIFY_API_URL}/playlists/${playlistId}/items`,
        { uris: chunk },
        {
          headers: {
            Authorization: `Bearer ${accessToken}`,
            "Content-Type": "application/json",
          },
        }
      );
    }
    console.log(`[Spotify] Added ${uris.length} tracks to playlist.`);
  } catch (err: any) {
    console.error(
      "[Spotify Error] addTracksToPlaylist failed:",
      err.response?.data || err.message
    );
    throw new Error("Failed to add tracks to Spotify playlist.");
  }
}

// ─── Main pipeline ────────────────────────────────────────────────────────────

async function generatePlaylistName(tracks: Track[]): Promise<string> {
  const trackList = tracks
    .slice(0, 8)
    .map((t) => `${t.title} by ${t.artist}`)
    .join(", ");
  try {
    const name = await getGroqText(
      `These songs are in a playlist: ${trackList}\n\nGive this playlist a short, creative, vibe-based name (2-4 words). No quotes, no explanation, just the name.`
    );
    return name || `Symphony Mix — ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;
  } catch {
    return `Symphony Mix — ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`;
  }
}

export async function generatePlaylist(
  tracks: Track[]
): Promise<GeneratePlaylistResponse> {
  const accessToken = await getAccessToken();


  console.log(`[Spotify] Searching ${tracks.length} tracks...`);
  const searchResults = await Promise.all(
    tracks.map((track) => searchTrack(track, accessToken))
  );

  const resolved: ResolvedTrack[] = [];
  const notFound: Track[] = [];

  searchResults.forEach((result, index) => {
    if (result) {
      resolved.push(result);
    } else {
      notFound.push(tracks[index]!);
    }
  });

  if (resolved.length === 0) {
    throw new Error(
      "None of the extracted tracks could be found on Spotify. Please try a different screenshot."
    );
  }

  const playlistName = await generatePlaylistName(tracks);

  console.log(`[Spotify] Creating playlist: "${playlistName}"`);
  const playlistId = await createPlaylist(accessToken, playlistName);

  const uris = resolved.map((t) => t.spotifyUri);
  console.log(`[Spotify] Adding ${uris.length} tracks...`);

  await addTracksToPlaylist(playlistId, uris, accessToken);

  await prisma.generatedPlaylist.create({
    data: {
      id: playlistId,
      playlistId: playlistId,
    },
  });

  const playlistUrl = `https://open.spotify.com/playlist/${playlistId}`;
  console.log(`[Spotify] ✅ Done: ${playlistUrl}`);

  return {
    playlistUrl,
    playlistId,
    playlistName,
    tracks: resolved,
    notFound,
  };
}

// ─── Step 2: Fetch playlist tracks ────────────────────────────────────────────

export function extractPlaylistId(url: string): string | null {
  const match = url.match(/playlist\/([a-zA-Z0-9]+)/);
  return match?.[1] ?? null;
}

export async function getPlaylistTracks(
  playlistId: string,
  accessToken: string
): Promise<{ id: string; title: string; artist: string }[]> {
  try {
    let allTracks: any[] = [];

    // Removed the strict 'fields' parameter. The new /items endpoint
    // altered the schema, so restricting it caused empty object returns.
    let url = `${SPOTIFY_API_URL}/playlists/${playlistId}/items?market=from_token&limit=100`;

    while (url) {
      const { data } = await axios.get(url, {
        headers: { Authorization: `Bearer ${accessToken}` },
      });
      if (data.items) {
        allTracks.push(...data.items);
      }
      url = data.next;
    }

    // mapping: gracefully handles the old 'track' wrapper,
    // the new 'item' wrapper, or a fully flattened response array.
    return allTracks
      .map((obj: any) => obj.track || obj.item || obj)
      .filter((t: any) => t && t.id)
      .map((t: any) => ({
        id: t.id,
        title: t.name || "Unknown Title",
        artist: t.artists ? t.artists.map((a: any) => a.name).join(", ") : "Unknown Artist",
      }));
  } catch (err: any) {
    console.error(
      "[Spotify Error] Exact details:",
      JSON.stringify(err.response?.data || err.message, null, 2)
    );
    throw new Error("Failed to fetch tracks from Spotify playlist.");
  }
}